/******************************************************************************

  nomlib - C++11 cross-platform game engine

Copyright (c) 2013, 2014 Jeffrey Carpenter <i8degrees@gmail.com>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

******************************************************************************/
#ifndef NOMLIB_SYSTEM_EVENTS_MOUSE_BUTTON_EVENT_HPP
#define NOMLIB_SYSTEM_EVENTS_MOUSE_BUTTON_EVENT_HPP

// #include "SDL.h"

#include "nomlib/config.hpp"

namespace nom {

/// \brief A structure containing information on a mouse button event.
struct MouseButtonEvent
{
  /// \brief The event type.
  ///
  /// \remarks SDL_MOUSEBUTTONDOWN or SDL_MOUSEBUTTONUP.
  uint32 type;

  /// \brief The mouse instance identifier, or SDL_TOUCH_MOUSEID.
  ///
  /// \remarks 'id' may be SDL_TOUCH_MOUSEID, for events that were generated by
  /// a touch input device, and not a real mouse. (You may want to ignore such
  /// events, if your application already handles SDL_TouchFingerEvent).
  uint32 id;

  /// \brief The X coordinate, relative to the nom::Window instance.
  int32 x;

  /// \brief The Y coordinate, relative to the nom::Window instance.
  int32 y;

  /// \brief The button that has changed.
  ///
  /// \remarks This field may be one of: SDL_BUTTON_LEFT, SDL_BUTTON_MIDDLE,
  /// SDL_BUTTON_RIGHT, SDL_BUTTON_X1 or SDL_BUTTON_X2.
  uint8 button;

  /// \brief The state of the button.
  ///
  /// \remarks SDL_PRESSED or SDL_RELEASED.
  uint8 state;

  /// \brief Value containing how many mouse buttons were clicked.
  ///
  /// \remarks One (1) for single-click, two (2) for double-click, and so on.
  ///
  /// \NOTE This field is not yet implemented and reserved for the release of
  /// SDL 2.0.2 (as per SDL2 wiki documentation).
  uint8 clicks;

  /// \brief The identifier of the window at the moment of the event.
  uint32 window_id;

  /// \brief The recorded time at the moment of the event.
  uint32 timestamp;
};

} // namespace nom

#endif // include guard defined
