/******************************************************************************

  nomlib - C++11 cross-platform game engine

Copyright (c) 2013, 2014 Jeffrey Carpenter <i8degrees@gmail.com>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

******************************************************************************/
#ifndef NOMLIB_LIBROCKET_SDL2_RENDERER_INTERFACE_HPP
#define NOMLIB_LIBROCKET_SDL2_RENDERER_INTERFACE_HPP

// #include <memory>

#include "nomlib/config.hpp"

#include <Rocket/Core/RenderInterface.h>

#include <SDL.h>

#include <OpenGL/glu.h>

#if !(SDL_VIDEO_RENDER_OGL)
    #error "Only the opengl sdl backend is supported. To add support for others, see http://mdqinc.com/blog/2013/01/integrating-librocket-with-sdl-2/"
#endif

namespace nom {

// Forward declarations
class RenderWindow;

class RocketSDL2Renderer: public Rocket::Core::RenderInterface
{
  public:
    RocketSDL2Renderer(SDL_Renderer* renderer, SDL_Window* screen, RenderWindow* window );

    /// Called by Rocket when it wants to render geometry that it does not wish to optimise.
    virtual void RenderGeometry(Rocket::Core::Vertex* vertices, int num_vertices, int* indices, int num_indices, Rocket::Core::TextureHandle texture, const Rocket::Core::Vector2f& translation);

    /// Called by Rocket when it wants to enable or disable scissoring to clip content.
    virtual void EnableScissorRegion(bool enable);
    /// Called by Rocket when it wants to change the scissor region.
    virtual void SetScissorRegion(int x, int y, int width, int height);

    /// Called by Rocket when a texture is required by the library.
    virtual bool LoadTexture(Rocket::Core::TextureHandle& texture_handle, Rocket::Core::Vector2i& texture_dimensions, const Rocket::Core::String& source);
    /// Called by Rocket when a texture is required to be built from an internally-generated sequence of pixels.
    virtual bool GenerateTexture(Rocket::Core::TextureHandle& texture_handle, const Rocket::Core::byte* source, const Rocket::Core::Vector2i& source_dimensions);
    /// Called by Rocket when a loaded texture is no longer required.
    virtual void ReleaseTexture(Rocket::Core::TextureHandle texture_handle);

  // FIXME:
  // private:
    /// \todo Rename to renderer_
    SDL_Renderer* mRenderer;

    /// \todo Rename to screen_
    SDL_Window* mScreen;

    RenderWindow* window_;
};

} // namespace nom

#include <Rocket/Core/Decorator.h>

#include "nomlib/math/Point2.hpp"
#include "nomlib/math/Size2.hpp"

namespace nom {

// Forward declarations
class IDecorator;

/// \see http://librocket.com/wiki/documentation/C%2B%2BManual/Decorators
/// \see http://librocket.com/wiki/documentation/RCSS/Decorators
class DecoratorFinalFantasyFrame : public Rocket::Core::Decorator
{
  public:
    DecoratorFinalFantasyFrame();
    virtual ~DecoratorFinalFantasyFrame();

    // bool Initialise(const Rocket::Core::String& image_source, const Rocket::Core::String& image_path);
    bool Initialise();

    /// Called on a decorator to generate any required per-element data for a newly decorated element.
    /// @param element[in] The newly decorated element.
    /// @return A handle to a decorator-defined data handle, or NULL if none is needed for the element.
    virtual Rocket::Core::DecoratorDataHandle GenerateElementData(Rocket::Core::Element* element);

    /// Called to release element data generated by this decorator.
    /// @param element_data[in] The element data handle to release.
    virtual void ReleaseElementData(Rocket::Core::DecoratorDataHandle element_data);

    /// Called to render the decorator on an element.
    /// @param element[in] The element to render the decorator on.
    /// @param element_data[in] The handle to the data generated by the decorator for the element.
    virtual void RenderElement(Rocket::Core::Element* element, Rocket::Core::DecoratorDataHandle element_data);

  private:
    std::unique_ptr<IDecorator> decorator_;
    // Point2i pos_;
    // Size2i dims_;
    // bool dirty_ = true;
};

} // namespace nom

#include <Rocket/Core/DecoratorInstancer.h>
// #include "nomlib/graphics/IDrawable.hpp"

namespace nom {

/// \see http://librocket.com/wiki/documentation/C%2B%2BManual/Decorators
/// \see http://librocket.com/wiki/documentation/RCSS/Decorators
class DecoratorInstancerFinalFantasyFrame : public Rocket::Core::DecoratorInstancer
{
  public:
    DecoratorInstancerFinalFantasyFrame();
    virtual ~DecoratorInstancerFinalFantasyFrame();

    /// Instances a decorator given the property tag and attributes from the RCSS file.
    /// @param name The type of decorator desired. For example, "background-decorator: simple;" is declared as type "simple".
    /// @param properties All RCSS properties associated with the decorator.
    /// @return The decorator if it was instanced successful, NULL if an error occured.
    Rocket::Core::Decorator* InstanceDecorator(const Rocket::Core::String& name, const Rocket::Core::PropertyDictionary& properties);

    /// Releases the given decorator.
    /// @param decorator Decorator to release. This is guaranteed to have been constructed by this instancer.
    void ReleaseDecorator(Rocket::Core::Decorator* decorator);

    /// Releases the instancer.
    void Release();
};

}

#endif // include guard defined
